### ISSUE TITLE
Split up Token Interface

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#965]
I'd like to propose that we split up the token interface into a set of small interfaces that tokens can choose to implement.

```rust
pub trait Interface {
    fn name(env: Env) -> Bytes;
    fn symbol(env: Env) -> Bytes;
    fn decimals(env: Env) -> u32;
    fn balance(env: Env, id: Address) -> i128;
    fn spendable_balance(env: Env, id: Address) -> i128;
    fn transfer(env: Env, from: Address, to: Address, amount: i128);
    fn transfer_from(env: Env, spender: Address, from: Address, to: Address, amount: i128);
    fn authorized(env: Env, id: Address) -> bool;
    fn allowance(env: Env, from: Address, spender: Address) -> i128;
    fn increase_allowance(env: Env, from: Address, spender: Address, amount: i128);
    fn decrease_allowance(env: Env, from: Address, spender: Address, amount: i128);
    fn burn(env: Env, from: Address, amount: i128);
    fn burn_from(env: Env, spender: Address, from: Address, amount: i128);
}
```

```rust
pub trait AdminInterface {
    fn admin(env: Env) -> Option<Address>;
    fn set_admin(env: Env, new_admin: Address);
    fn mint(env: Env, to: Address, amount: i128);
    fn clawback(env: Env, from: Address, amount: i128);
    fn set_authorized(env: Env, id: Address, authorize: bool);
}
```

This issue was first posted and discussed on Discord at:
- https://discord.com/channels/897514728459468821/1114325793926037605

**Comment by leighmcculloch** [comment]
We will have a challenge implementing this in the SDK, because the SDK currently doesn't support very well a contract implementing multiple traits. We've really gotta deal with that, but if we do, the above would be pretty smooth.

There's an issue open for dealing with it:
- #268 

The path I suggest to implementing the above would be:


```[tasklist]
### Tasks
- [ ] Break up the interface per above. (So we can start referring to these separately, and start SEPifying them.)
- [ ] Join them back together into a super interface temporarily (to retain existing behavior)
- [ ] Get out the 💪🏻 and fix the multi-trait support: #268
- [ ] Remove the super interface. 
```
