### ISSUE TITLE
Replace Address::from_contract_id with from_str

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#996]
### Proposal

I propose that we replace `Address::from_contract_id` with `Address::from_str`.

### Why

Folks are using the `Address::from_contract_id` function to hardcode addresses into contracts to reduce the need for bumping data storage, and avoiding loading additional storage keys, etc.

The `from_contract_id` function unfortunately causes contracts to start depending on the different types of addresses, when addresses are intended to be opaque to improve interoperability across address types.

Regardless of whether hardcoding values or not is ideal, we should remove `from_contract_id` and replace it with a function that retains the opaque quality of addresses.

Related thread https://discord.com/channels/897514728459468821/1118888566349631561

### How

`from_str` would accept a `&str`, or possibly `&'static str`, that contains an address strkey, e.g. `G...` or `C...`. The function would make a single host function call to the host passing the location of the address in linear memory, for the host to read, similar to how the `vec_new_from_linear_memory` does. The host function would return an `AddressObject`, and the SDK function would return an `Address`.

It would also be good to add a similar function like `to_string()` for the reverse, although this would likely only be used in `Debug` implementations.

Importantly, contracts shouldn't need to perform any decoding or conversion, such as base32 decoding or decoding strkeys.

cc @dmkozh @graydon 
```[tasklist]
### Tasks
- [ ] Add `address_from_string_in_linear_memory` and `address_to_string` host fns to environment
- [ ] Add `Address::from_str` to sdk
- [ ] Add `Address::to_string` to sdk and use in `Debug` impl of Address
- [ ] Remove `Address::from_contract_id`
- [ ] Remove any other lingering testutils supporting Address conversion from other types
```

**Comment by leighmcculloch** [comment]
@graydon I'm not sure if there's an optimization opportunity here, but these functions in WASM built contracts would primarily / only be used for hardcoded str values Would there be some advantage to making the function accept only `'static` strings, such as being able to copy the value to the host even more efficiently than we do already when copying linear memory to the host? I assume no, but just want to check.

**Comment by leighmcculloch** [comment]
More new conversations about the issues that this change will support:
- https://discord.com/channels/897514728459468821/1145458616086843423
- https://discord.com/channels/897514728459468821/1121029750912204840

**Comment by esteblock** [comment]
I would like tho see this support.
Sometimes we would like to check if some contract address is correct, but we only know it's the address string:


In `test.rs` I have:

```rust
fn native_asset_contract_address(e: &Env) -> Address {
    let env = Env::default();
    let native_asset = Asset::Native;
    let contract_id_preimage = ContractIdPreimage::Asset(native_asset);
    let bytes = Bytes::from_slice(&e, &contract_id_preimage.to_xdr().unwrap());
    let native_asset_address = Address::from_contract_id(&e.crypto().sha256(&bytes));
    native_asset_address
}
.
.
.
// Set the native token address
let native_address =native_asset_contract_address(&e);
let expected_address_string="CDF3YSDVBXV3QU2QSOZ55L4IVR7UZ74HIJKXNJMN4K5MOVFM3NDBNMLY";
assert_eq!(native_address, expected_address_string);
```

But I get:
```
--> src/test.rs:49:5
   |
49 |     assert_eq!(native_address, expected_address_string);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     expected `Address`, found `&str`
   |     expected because this is `soroban_sdk::Address`
```
It's obvious because they are not the same.... but it would great if we could build an Address object from the string

**Comment by dmkozh** [comment]
SDK support has been added in https://github.com/stellar/rs-soroban-sdk/pull/1112
